In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([
            ['green', 'M', 10.1, 'class1'], 
            ['red', 'L', 13.5, 'class2'], 
            ['blue', 'XL', 15.3, 'class1']])

In [4]:
df.columns = ['color', 'size', 'prize', 'class label']

In [5]:
size_mapping = {
           'XL': 3,
           'L': 2,
           'M': 1}

In [6]:
df['size'] = df['size'].map(size_mapping)

In [7]:
df

color  size  prize class label
0  green     1   10.1      class1
1    red     2   13.5      class2
2   blue     3   15.3      class1

In [8]:
class_mapping = {label:idx for idx,label in enumerate(set(df['class label']))}
df['class label'] = df['class label'].map(class_mapping)

In [9]:
df

color  size  prize  class label
0  green     1   10.1            0
1    red     2   13.5            1
2   blue     3   15.3            0

In [13]:
import numpy as np
index = np.array([0,2])
index

array([0, 2])

In [18]:
df.iloc[index]

color  size  prize  class label
0  green     1   10.1            0
2   blue     3   15.3            0

In [36]:
y_test = np.array([1,0,1,0,1,1,1,1,1,0,0,1,0,1]).reshape(-1,1)

In [37]:
y_pre = np.ones([len(y_test),1])

In [38]:
y_test.shape

(14, 1)

In [39]:
y_pre.shape

(14, 1)

In [41]:
(y_pre==y_test).sum()

9

In [19]:
s = pd.Series(list('abca'))
s

0    a
1    b
2    c
3    a
dtype: object

In [20]:
s.iloc[index]

0    a
2    c
dtype: object

In [10]:
pd.get_dummies(s)

a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

In [1]:
import sklearn

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
f = np.array([[1, 2], [3, 4]])
d = f
f

array([[1, 2],
       [3, 4]])

In [5]:
d*f

array([[ 1,  4],
       [ 9, 16]])

In [6]:
d @ f

array([[ 7, 10],
       [15, 22]])

In [7]:
np.dot(d,f)

array([[ 7, 10],
       [15, 22]])

In [8]:
d.dot(f)

array([[ 7, 10],
       [15, 22]])

In [10]:
np.multiply(d,f)

array([[ 1,  4],
       [ 9, 16]])

In [11]:
t = np.matrix([[1, 2], [3, 4]])
k = t
t

matrix([[1, 2],
        [3, 4]])

In [12]:
k*t

matrix([[ 7, 10],
        [15, 22]])

In [13]:
k @ t

matrix([[ 7, 10],
        [15, 22]])

In [14]:
np.multiply(k, t)

matrix([[ 1,  4],
        [ 9, 16]])

In [15]:
np.dot(k, t)

matrix([[ 7, 10],
        [15, 22]])

In [17]:
k.dot(t)

matrix([[ 7, 10],
        [15, 22]])

In [18]:
sum(f)

array([4, 6])

In [19]:
f

array([[1, 2],
       [3, 4]])

In [20]:
np.sum(f)

10

In [21]:
sum(t)

matrix([[4, 6]])

In [23]:
a = [1,1,1,1,1,1,1,1]

In [24]:
b = np.array(a)
b

array([1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
b=[[1,2,3], [5,8], [7,8,9]]

In [28]:
from itertools import chain

In [29]:
c=list(chain(*b))

In [30]:
print(c)

[1, 2, 3, 5, 8, 7, 8, 9]


In [31]:
arr = np.ones([5,1])

In [32]:
arr

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [33]:
alei = list(chain(*arr))
alei

[1.0, 1.0, 1.0, 1.0, 1.0]

In [42]:
import numpy as np
import pandas as pd

In [43]:
a = np.ones([10,1])
a

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [49]:
submit = pd.DataFrame(a)
submit.columns=['is_pass']
submit

is_pass
0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
5      1.0
6      1.0
7      1.0
8      1.0
9      1.0